atymic/twitter

src/Thujohn/Twitter/Twitter.php

This fixes the required parameters for a few list related methods:
* `postListCreateAll()` [docs](https://dev.twitter.com/rest/reference/post/lists/members/create_all)
* `postListMember()`
* `destroyList()`
* `postListUpdate()`
* `destroyListMembers()`
The list can be specified by either `list_id` *or* `slug`, but this class is requiring *both* parameters.

Fix logic check for required parameters in some of the list API methods

---

src/Thujohn/Twitter/Traits/MediaTrait.php

According to the Twitter API [documentation](https://dev.twitter.com/rest/reference/post/media/upload), you can either pass `media` or `media_data` parameters when uploading an image, but not both at the same time. 
Fixed this validation.

Fixing twitter media upload API parameters validation.

---

README.md

By using the --provider option on the vendor:publish command we can indicate the Service Provider for which we want configuration files to be published, avoiding publish files from other packages that the user might or might not want.

Change publish command so it only publishes the package files

---

composer.json

PHP version required is 5.5 at least to work with `Class::class`.
See thujohn@762afe9.
See http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class.

Fix php version required by 2.1.4+

---

README.md

The current documentation suggests calling:
```php
$credentials = Twitter::getCredentials([
'email' => 'true',
]);
```
to get the user's email address. The correct array key is actually `include_email`. This PR corrects it.

Fix reference to include_email param

---

src/Thujohn/Twitter/Traits/AccountTrait.php
src/Thujohn/Twitter/Traits/BlockTrait.php
src/Thujohn/Twitter/Traits/DirectMessageTrait.php
src/Thujohn/Twitter/Traits/FavoriteTrait.php
src/Thujohn/Twitter/Traits/FriendshipTrait.php
src/Thujohn/Twitter/Traits/GeoTrait.php
src/Thujohn/Twitter/Traits/HelpTrait.php
src/Thujohn/Twitter/Traits/ListTrait.php
src/Thujohn/Twitter/Traits/MediaTrait.php
src/Thujohn/Twitter/Traits/SearchTrait.php
src/Thujohn/Twitter/Traits/StatusTrait.php
src/Thujohn/Twitter/Traits/TrendTrait.php
src/Thujohn/Twitter/Traits/UserTrait.php
src/Thujohn/Twitter/Twitter.php

The proposed pull request contains changes which move away from the base Exception in php and aims to provide more semantic meaning to the exceptions thrown by the library.
Where possible it should be avoided to throw and catch the base Exception. This finer grained control allows developers to catch only the errors they expect to happen and allow their exception handlers to deal with those that they don't.
These changes should be backwards compatible with all code already written as all exceptions used extend the base Exception which means they will be caught by existing catch statements. Due to these backwards compatibility concerns i left the unit tests as expecting Exception (as this is what is expected to be backwards compatible).
http://php.net/manual/en/spl.exceptions.php
If there …

Changed exceptions to be more specific ones provided by PHP's SPL.

---

src/Thujohn/Twitter/Traits/ListTrait.php

... as this method only returns the Statuses of one specified List, not many Lists. Matches the naming of the other methods.

Rename `getListsStatuses` to `getListStatuses`

---

src/Thujohn/Twitter/Traits/StatusTrait.php
src/Thujohn/Twitter/Twitter.php

Use the Twitter publish resource for oEmbed requests, because it is not rate limited and add important documentation on some parameters for Tweet-retrieval (Tweets are truncated by default now).
Related links:
https://dev.twitter.com/rest/reference/get/statuses/oembed
https://dev.twitter.com/overview/api/upcoming-changes-to-tweets#overview
Thanks for this library!

Change important API updates

---

composer.json

The facade should be auto discovered along side the service provider. 
Closes #276

fix: autoload facade

---

src/Traits/AuthTrait.php
src/Traits/DirectMessageTrait.php
src/Twitter.php

Fix unsupported media type issue in certain situations such as posting direct messages.
ref: #295 
---
By introducing a _request_format_ option we can ensure requests are made in the correct formats, irrespective of desired response format.

Fix: unsupported media type 

---

README.md
src/Traits/AuthTrait.php
src/Traits/DirectMessageTrait.php
src/Twitter.php

Follow-up to fix unsupported media type (#295)
---
With this change the following works:
```php
$data = [
'format' => 'json',
'request_format' => 'json',
'event' => [
'type' => 'message_create',
'message_create' => [
'target' => [
'recipient_id' => $recipient
],
'message_data' => [
'text' => 'Happy New Year!'
]
]
]
];
try
{
$response = Twitter::post('direct_messages/events/new', $data);
} catch (Exception $exception) {
// ...
}
```
or 
```php
$data = [
'format' => 'json',
'event' => [
'type' => 'message_create',
'message_create' => [
'target' => [
'recipient_id' => $recipient
],
'message_data' => [
'text' => 'Happy New Year!'
]
]
]
];
try
{
$response = Twitter::postDm($data);
} catch (Exception $exception) {
// ...
}
```
**Note:** `request_format` must be explicitly set when calling …

Allow specifying request format separately from response format

---

src/Thujohn/Twitter/Traits/UserTrait.php

Added postUsersLookup() method for larger requests of 10 to 100 accounts, Twitter recommends using POST instead of GET for large requests as GET returns if you query 10+ users.

Switch getUsersLookup() to use POST method

---

src/Thujohn/Twitter/Twitter.php

In linkify() if $tweet['text'] is not found, use $tweet['full_text']

---

README.md

As per docs: https://laravel.com/docs/6.x/upgrade#the-input-facade
Input no longer exists. Either use the Request facade or alias that instead of Input.
[Source](https://laracasts.com/discuss/channels/laravel/laravel-6-class-illuminatesupportfacadesinput-not-found?reply=534800)

Fixed: Class 'Input' not found

---

CHANGELOG.md
src/ApiV1/Traits/StatusTrait.php
tests/Unit/ApiV1/Service/TwitterTest.php

fix: oembed query not working

---

CHANGELOG.md
src/ApiV1/Service/Twitter.php
src/ApiV1/Traits/AuthTrait.php
src/ApiV1/Traits/DirectMessageTrait.php
src/ApiV1/Traits/TrendTrait.php
src/Http/Client/SyncClient.php
src/Twitter.php

fix: error in auth trait import

---

src/ApiV1/Service/Twitter.php
src/Concern/ApiV2Behavior.php
src/Contract/Twitter.php
src/Service/Accessor.php
tests/Unit/AccessorTestCase.php
tests/Unit/Service/AccessorTest.php

This ensures that the same instance of accessor is resolved by the twitter facade/contract.

fix: ensure Twitter facade resolves as singleton (fixes #349)

---

src/ApiV1/Service/Twitter.php
src/Concern/HotSwapper.php
src/Service/Accessor.php
src/Twitter.php
tests/Unit/Service/AccessorTest.php

This exposes `forApiV1()` and `forApiV2` methods which were not previously available on Twitter service.
Fixes: #355

fix: unable to switch API version on service #355

---

src/Concern/HotSwapper.php
src/Twitter.php
tests/Unit/AccessorTestCase.php
tests/Unit/Concern/HotSwapperTest.php

fix: hotswapping methods forApiV1() and forApiV2()

---

src/Contract/Http/SyncClient.php
src/Contract/Querier.php
src/Http/Client.php
src/Http/Client/SyncClient.php
src/Service/Querier.php
tests/Unit/Http/Client/SyncClientTest.php
tests/Unit/Service/QuerierTest.php

Fixes #358 
Added a `getSyncClient()` method to `Querier` and added a `getResponse()` method to `SyncClient`. This allows you to access the last response including the headers.
I did not add anything to `AsyncClient` since I wasn't sure how that would work since it returns a Promise.
I wasn't sure the best way to update the tests so let me know if I should change anything. I wanted to test that the response is still set when there is an exception but couldn't figure out how to test that with the mocked objects.

Ability to get the last response

---

src/ApiV1/Traits/FormattingHelpers.php

The changes herein:
- fix user linking for mentions at the start of the tweet
- all specifying whether hashtags, users, or emails should be linkified. (by default these are set to `true` for backward compatibility)

Allow specifying whether hashtags, users, or emails should be "linkified". Fixes #205

---

README.md
src/Concern/TweetCounts.php
src/Contract/Twitter.php
src/Service/Accessor.php
tests/Unit/Concern/TweetCountsTest.php

The changes herein:
1. expose the new tweet count [endpoints](https://developer.twitter.com/en/docs/twitter-api/tweets/counts/api-reference)
2. add notes and example on how to use newly added v2 endpoint
ref: #365

Expose new tweet count endpoints, ref: #365

---

README.md
src/ApiV1/Service/Twitter.php
src/ApiV1/Traits/AccountActivityTrait.php
src/Contract/Http/SyncClient.php

This re-introduces the missing AccountActivityTrait for API v1.
---
issue: #368  
prev. ref: https://github.com/atymic/twitter/pull/286

fix: re-add account activity trait

---

composer.json

Now that the upstream library fixed PSR7 compat.
Closes #371

fix: bump guzzle oauth version

---

.github/workflows/php.yml

This should fix the action I broke in #387.
My apologies.

Exclude Laravel 9 on PHP 7

---

README.md

Clarify default response format nuance.

fixes: #383

---

src/ApiV1/Traits/FormattingHelpers.php

changed regex to use `\s` for whitespace

Detect preceding whitespace for users in linkify

---

src/ApiV1/Traits/FormattingHelpers.php

Using ${var} in strings is deprecated, use {$var} instead

Fix PHP 8.2 deprecation with ${var} in strings
